if(EXISTS "/home/jliu17/000_Projects/04-Working/FEM3D/build_cpu/unit_tests[1]_tests.cmake")
  include("/home/jliu17/000_Projects/04-Working/FEM3D/build_cpu/unit_tests[1]_tests.cmake")
else()
  add_test(unit_tests_NOT_BUILT unit_tests_NOT_BUILT)
endif()
